const express = require('express');
const app = express();
const router = require('./routes/api');
const bodyParser = require('body-parser');
require('dotenv').config();
const PORT = process.env.PORT || 8080;
const cors = require('cors');
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(router);
app.listen(PORT, () => console.log(`Server Running on PORT: ${PORT}`));